services:
  webserver-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - buildno
        - gitcommithash
    depends_on:
      - database-dev
      - cache-dev
    tmpfs:
      - /app/logs:uid=1000,gid=1000
      - /app/tmp:uid=1000,gid=1000
      - /app/vendor:uid=1000,gid=1000,exec
    volumes:
      - ./:/app
    working_dir: /app/
    environment:
      DATABASE_URL: postgres://postgres@database-dev/watcher_nms
    ports:
      - 80:80/tcp

  database-dev:
    image: postgres
    tmpfs:
      - /var/lib/postgresql/data:exec
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: watcher_nms
    ports:
      - 5432:5432/tcp

  cache-dev:
    image: redis
    tmpfs: 
      - /data:exec
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
