# syntax=docker/dockerfile:1

FROM webdevops/php-nginx-dev:8.3-alpine

ARG buildno
ARG gitcommithash

RUN echo "Build number: $buildno"
RUN echo "Based on commit: $gitcommithash"

ENV DEBUG "true"
ENV WEB_DOCUMENT_ROOT "/app/webroot"

# Install PHP-SNMP extension
RUN set -x \
 && apk add -U --no-cache net-snmp-dev \
 && docker-php-ext-configure snmp \
 && docker-php-ext-install -j$(nproc) snmp \
 && docker-run-bootstrap \
 && docker-image-cleanup

# Add on-start commands
RUN echo '# Composer oprations' >> /opt/docker/provision/entrypoint.d/99-composer.sh \
 && echo 'gosu "${APPLICATION_USER}" composer install -d /app' >> /opt/docker/provision/entrypoint.d/99-composer.sh \
 && echo 'gosu "${APPLICATION_USER}" composer run-script migrations -d /app -- --no-lock' >> /opt/docker/provision/entrypoint.d/99-composer.sh \
 && echo 'gosu "${APPLICATION_USER}" composer run-script schema-cache -d /app' >> /opt/docker/provision/entrypoint.d/99-composer.sh
