# syntax=docker/dockerfile:1

FROM webdevops/php-nginx:8.4-alpine

ARG buildno
ARG gitcommithash

RUN echo "Build number: $buildno"
RUN echo "Based on commit: $gitcommithash"

ENV DEBUG "true"
ENV WEB_DOCUMENT_ROOT "/app/webroot"

# Install PHP-SNMP extension
RUN set -x \
 && apk add -U --no-cache net-snmp-dev \
 && docker-php-ext-configure snmp \
 && docker-php-ext-install -j$(nproc) snmp \
 && docker-run-bootstrap

# Add on-start commands
RUN cat <<'EOF' > /opt/docker/provision/entrypoint.d/99-composer.sh
# Composer operations
gosu "${APPLICATION_USER}" composer install -d /app
gosu "${APPLICATION_USER}" composer run-script migrations -d /app -- --no-lock
gosu "${APPLICATION_USER}" composer run-script schema-cache -d /app
EOF
