<?php
/**
 * Default settings (baseline template).
 *
 * This file provides the baseline configuration values that the SettingsService
 * loads as a fallback when no value is stored in the database. Treat these values
 * as a TEMPLATE / reference example — not as your live configuration.
 *
 * HOW TO CUSTOMIZE (IMPORTANT):
 * Do NOT edit this file to configure your installation. It is versioned and may be
 * overwritten on upgrades, so changes made here can be lost. Instead, override the
 * values you need in the database via the Settings UI (or programmatically through
 * SettingsService::set()). Database overlays always take precedence over these
 * defaults (priority: DB > defaults).
 *
 * The shipped values are oriented to a Czech (CZ) company and serve as a working
 * example. Tailor them to your own organization through the settings UI.
 *
 * Structure:
 * - Top-level keys represent plugin namespaces (e.g. 'core', 'radius', 'bookkeeping').
 * - Each plugin contains one or more logical blocks (keys), which may contain nested values.
 * - Values can be scalars or arrays, and may use env() to allow environment-specific overrides.
 *
 * Example:
 * [
 *     'core' => [
 *         'company' => [
 *             'name' => env('APP_COMPANY', 'NETAIR s.r.o.'),
 *             'timezone' => 'Europe/Prague',
 *         ],
 *     ],
 * ]
 *
 * Notes:
 * - Secrets and credentials belong in environment variables, not in the database.
 * - This file is a declarative source of truth for default values only.
 * - A value that is not a plain scalar says what it is: wrap it in a SettingType
 *   (ListType, BoolType, ...). A declared setting is drawn accordingly in the
 *   settings UI, is checked before it is stored, and is overlaid whole rather
 *   than merged into item by item.
 * - Declare them with named arguments (default:, hint:, ...), so what each value
 *   is for can be read off the line it stands on.
 */

use Settings\ValueObject\Type\ListType;

return [
    'core' => [
        'devices' => [
            'ignored_ip_link_ranges_list' => ListType::ofStrings(
                default: [
                    '192.168.0.0/16',
                ],
                hint: __('IP ranges left out when devices are linked by their neighbouring addresses.'),
            ),
        ],
    ],
];
